### ISSUE TITLE
 VerveineJ exception on wrong command line

### ISSUE THREAD

**Issue by seandenigris** [moosetechnology/Moose#1053]
Originally reported on Google Code with ID 1053

```
Describe the problem: what do you get? what do you expect?

When we execute VerveineJ with an wrong command line, we get :

Exception in thread "main" java.lang.IllegalStateException: invalid environment
settings
        at org.eclipse.jdt.core.dom.ASTParser.getClasspath(ASTParser.java:256)
        at org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:988)
        at fr.inria.verveine.extractor.java.VerveineJParser.parse(Unknown Source)
        at fr.inria.verveine.extractor.java.VerveineJParser.main(Unknown Source)

Instead of a message such as:
Error: a wrong command line parameter is set

How to reproduce the problem: step by step if necessary

Launch VerveineJ with a wrong parameter (-h to list the aloowed parameters)

Additional information: platform, context which may impact the problem

Windows 7 - x64 

Please fill in the labels with the following information:
* Type-Enhancement
* Component-VerveineJ

```

Reported by `v.blondeau92` on 2014-03-10 11:00:53

**Comment by girba** [comment]
VerveineJ is now replaced by jdt2famix
